{% set version = "0.0-4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-assertive.code
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/assertive.code_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/assertive.code/assertive.code_{{ version }}.tar.gz
  sha256: 2f820474ed20e06f65b284962c87cd1e85220a11cc7fcde09716f0eee5821387

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-assertive.base >=0.0_2
    - r-assertive.properties
    - r-assertive.types
  run:
    - r-base
    - r-assertive.base >=0.0_2
    - r-assertive.properties
    - r-assertive.types

test:
  commands:
    - $R -e "library('assertive.code')"           # [not win]
    - "\"%R%\" -e \"library('assertive.code')\""  # [win]

about:
  home: https://bitbucket.org/richierocks/assertive.code
  license: GPL-3.0-or-later
  summary: A set of predicates and assertions for checking the properties of code. This is mainly for use by other package developers who want to include run-time testing features in their own packages. End-users will usually want to use assertive directly.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr

# Package: assertive.code
# Type: Package
# Title: Assertions to Check Properties of Code
# Version: 0.0-3
# Date: 2018-10-21
# Author: Richard Cotton [aut, cre]
# Maintainer: Richard Cotton <richierocks@gmail.com>
# Authors@R: person("Richard", "Cotton", role = c("aut", "cre"), email = "richierocks@gmail.com")
# Description: A set of predicates and assertions for checking the properties of code. This is mainly for use by other package developers who want to include run-time testing features in their own packages. End-users will usually want to use assertive directly.
# URL: https://bitbucket.org/richierocks/assertive.code
# BugReports: https://bitbucket.org/richierocks/assertive.code/issues
# Depends: R (>= 3.0.0)
# Imports: assertive.base (>= 0.0-2), assertive.properties, assertive.types, methods
# Suggests: testthat
# License: GPL (>= 3)
# LazyLoad: yes
# LazyData: yes
# Acknowledgments: Development of this package was partially funded by the Proteomics Core at Weill Cornell Medical College in Qatar <http://qatar-weill.cornell.edu>.  The Core is supported by 'Biomedical Research Program' funds, a program funded by Qatar Foundation.
# Collate: 'imports.R' 'assert-is-code.R' 'is-code.R'
# RoxygenNote: 6.1.0
# NeedsCompilation: no
# Packaged: 2018-10-21 18:26:19 UTC; richierocks
# Repository: CRAN
# Date/Publication: 2018-10-21 19:00:02 UTC
