travis:
  secure:
    BINSTAR_TOKEN: HaSP2NIgr31iwJK4LrOavAbCLw+FUyUyqKgeDNTWzst/42MEZXjbR/z4e7GynoQ8SHUw3R1PjyBAJGkWsMxbzdNLTEzjnO/nSQx6x0XmyCi+tZzwDJua82rDubZSDwjOjmylhlr+onAV6L8XGLWAbC4V59tABORNlSrH+Dcz+fopX+hLMKny9zXXKXYknlM9X7gnQWUq7HM8gMvgKjOORqPiAJR2P2/8eRiPE3HObUdbqC0EyaozZmPslLJZRUwmR0E5toY0d7+1qvkeG+Bba8j8nG/lzi8vVX5Xvbd8wTmVEYBwk4o9d38JT5vF81NTyK7pDqu3HMgZBC2Gg8bKYiuprhzhhlvuxwj7kJ4oTrL5L+/5asRSdHitfYGY3WFhT0WkVYdAJlOEr32R5OAgErFhUI8Pvn6CQlE/0KvOYiV5yqIQcCvqq16F4rddFzMYbyg1NWEgLrLmutyeOerwBFLlQXLFNZtg+11wewCG7atdANhj/I6A30+blBjlffJNbqqr0ghf9BbVWLTjFgc7jR9epESJghVrKZ6GM48UdK6peYTu2viDcodS2FHI30UdUz8QWKvdMW+XNYKeGN66V+iJUqdMUBtKxDOsYJ2kfCRVRBoYWRrunFw0z7rwcjQHF8cE1/N85aaEdNKt1S486WWAvSK4ai/l5vIC3xNVQjA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
