travis:
  secure:
    BINSTAR_TOKEN: L4uy8Nx+BEk0dDDgsf6+NJ2475h0C/LtxO8Zqk3kN0wIL2BX75i2c0Z9k8RtWMMWIx3mXeoWNN5WUcuv9HLcqVTe/koG3MTgSwbo/6OFVnhrMXcZqx8F5OADhYOVWzy7H9lcUFHQFAPSTTO3Hfd0qrdO7M3s0KBwmU0YIqKmUZk0ZWbO5vCvrEueiEL6X2TInnrXPIwY2Ugp4BrzP7E+BGhyAYdLn2lBfbGG5vwKWy04ORE4X/e+wUzdeiQAxTmJkPeIHKU4UHDxfsgB20eRqpnQBSmRq8GCoZxYsMOwASfvp6Eo8wBcbDFqTKdqqLmjJrgQHEQ9jD9/4EYjIT7y3thp06M4wcezInChdQa0xFz8sfv3bOc6+I3egggWILr5kEByujXmt59iHacq/+gaksp7qJz5CQpNBoCMu4YUE9NEopyIMgNkdGtDKZfG+pI/O4JRoQHfoznUHti+p7XqfkW5HPnnoqs3AGGVJ9V7LRvl+Kw7PdBjdjqflEuZ+fF6KPowzqs/FlazRTzlOpP7dZm0I1OwDl5rq6imz6eKv2lVH/WLv31qppRbeGOlT33E9FK/OrMcajnBhBu3BOG544TuZIWMvwAAC/1iXrGu5aPSbhUa1Yt8ur+adjrzjZpdccrw0ZO1AV2jN++lcBPfHwYJ19f/DYjobAm2HfozK1A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
