travis:
  secure:
    BINSTAR_TOKEN: gElb7zaMa4VAy7h9gbcKa1ETvrOGP760LuR7MbLxBVa7OV2IuNG8Extt48z/tMInDnVDvAJteJv9hobwNSKG0MXcqlDmcRIYXcvb4hvK/XC71/g267d1s9Fow2PObzWW04NyJEVzd7pJf5/4KZT4yH31eL1xbtlmEm7Vmp+qCEpwH2edG6TFDwkJj82EM5EwAExGwj5EfX85hjs7Yck7EJrbsIknmloNTSPy40aU5Up2wKmc5GOIxh5pZxnGoOvK3IceXwITfgZR7LrhUxtNWP7ba2In7og41+QpNIQfZjPG62zOu8/SrFV+8SYr+mvYZ7UYtKwxu4wWcz/zJH3f+YtCcOxVs6B3diZi8frOxQxaHDNJia8zfuQ51krD73xcw8zcuywobPCXw9SGwn/xZhoZaGWXYHjv8OxQ9sY3zC6wMhNF8O1j27sg79yQm/9j6qbEL47l9u00GmkLKhmarbkZe4pd2Fpkw4Da7SFoerVgsK/OxZIOgn7fBrbIAEFStfZIpVbyFgrVew1WSb+AX40quAfKgcwfokEv/6H3LdjP5pdIa3dW7kbK3YKE67s/CCq2dObNhMqicvOckvw31yevso2cfN4MyHRzS9eSSu/aH629A86FtkaJZGX13TxscH6Gv+Yop72td6i+u+d+6qn9WiLY1XzLVInPqVQ0C8k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
